### ISSUE TITLE
Checkbox can't be checked when refreshing the same page

### ISSUE THREAD

**Issue by gkkirilov** [creativetimofficial/vue-argon-design-system#11]
Steps to replicate: 1. Visit page with a checkbox 2.Refresh the page 3.Try to click on checkbox and its not working
It can even be replicated here https://demos.creative-tim.com/vue-argon-design-system/documentation/components/buttons.html

**Comment by gkkirilov** [comment]
Hey @timcreative can you help me with this one?
I would be happy if you can point me to the part in the code where I should look for fixing this. 💯

**Comment by dhonions** [comment]
Just looking at the page you referenced I can replicate the error on the page - on refresh it seems that the label of the checkbox does not match the element id it is referencing.  If you change the label for='' to match the checkbox id it fixes the issue - so I'd start debugging there.    Sorry can't be more help, but I was just passing :)

**Comment by cristijora** [comment]
Closing as it was resolved by moving id asignment to `mounted`. Also replaced the id generator with a more reliable function. The old one could generate numbers between characters which are not valid as id attributes in html
