### ISSUE TITLE
Error in manifest.json

### ISSUE THREAD

**Issue by Atiladanvi** [creativetimofficial/vue-argon-design-system#17]
When i run npm run server this error is shown in console of browser : Manifest: Line: 1, column: 1, Unexpected token.

**Comment by Hajni83** [comment]
Same issue here. Is there any solution?

**Comment by Atiladanvi** [comment]
I don't have idea what is that. I will try found the solution. Keep trying too.

**Comment by noreason** [comment]
Out of the box there doesn't seem to be a manifest file, you can learn a bit more about them here:
https://developers.google.com/web/fundamentals/web-app-manifest/

**Comment by Atiladanvi** [comment]
Just added manifest.json in public path and include in index html ` <link rel="manifest" href="manifest.json">`
```javscript{
  "short_name": "Vue Argon",
  "name": "Vue Argon Design System",
  "icons": [
    {
      "src": "/public/img/brand/white.png",
      "type": "image/png",
      "sizes": "100X30"
    }
  ],
  "start_url": "/public"
}
