### ISSUE TITLE
npm install process includes numerous deprecated and vulnerable packages

### ISSUE THREAD

**Issue by benlove** [creativetimofficial/vue-argon-design-system#4]
Hi,
when installing current (1.0.0) version of Argon using npm install, several error messages are shown:
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated gulp-util@0.0.1: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.12: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.0: Use uuid module instead
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js

Can the install setup be updated to reflect latest, secure updates?
Thanks
Ben

**Comment by cristijora** [comment]
Hello @benlove 
Before going further, are you using the simple [html version](https://github.com/creativetimofficial/argon-design-system) or the Vue one? 

I'm pretty sure the Vue one (this repo) doesn't have any gulp dependencies whatsover so this issue might be related to this repo actually https://github.com/creativetimofficial/argon-design-system

**Comment by benlove** [comment]
You're right - wrong repo. Sorry. Will redo under Argon Design System. Thanks!
