### ISSUE TITLE
IE11 blank page issue

### ISSUE THREAD

**Issue by bmrankin** [creativetimofficial/vue-argon-design-system#5]
Thanks for the work on the template. I look forward to the PRO version.

I have a client that relies heavily on IE.

The pages rendered mostly blank or with missing components.

There were some compiling issues showing up in connection with [Object.assign()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign)

Are you expereincing this in your builds?

I had to add the following polyfills in the babel.config.js to get it to work.

```
module.exports = {
      presets: [
        ['@vue/app', {
          polyfills: [
            'es6.promise', // pages would partilally load // already default included now
            'es6.array.iterator', // pages would partilally load // already default included now
            'es6.symbol',
            'es6.object.assign'  // this is the one that finally allowed it to completely build
          ]
        }]
      ]
    }
```

Thoughts?

**Comment by yiss** [comment]
To solve this issue : 
`npm install babel-polyfill`
and import it into your app main entry point with `import 'babel-polyfill'`

**Comment by cristijora** [comment]
IE issues should be fixed now. These polyfills should be enough to add support of IE
```js
    [
      "@vue/app",
      {
        "polyfills": ["es7.object.entries", "es6.promise"]
      }
    ]

```
However there's still one UI issue with images which is pending a fix.

@yiss your approach is good as well but adds some extra code which will be downloaded by all browsers
