### ISSUE TITLE
error in module build

### ISSUE THREAD

**Issue by davidWebmaster** [creativetimofficial/vue-argon-design-system#6]
how to solve this?
![screen shot 2018-09-02 at 22 54 23](https://user-images.githubusercontent.com/3306913/44963800-5162eb00-af03-11e8-8e24-05157093b414.png)

**Comment by cristijora** [comment]
@davidWebmaster Changing the imports to:

```
@import "./mixins/alert.scss";
@import "./mixins/badge.scss";
@import "./mixins/background-variant.scss";
@import "./mixins/buttons.scss";
@import "./mixins/forms.scss";
@import "./mixins/icon.scss";
@import "./mixins/modals.scss";
@import "./mixins/popover.scss";

```
Should fix the problem. Update the code to this as well for this part
